import "./globals.css";
import { playfair, roboto } from "./fonts";
import Providers from "./Providers";
import Header from "./components/Header";
import { LayoutProvider } from "./LayoutProvider";

export const metadata = {
  title: "React News App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <Providers>
        <body className={`${playfair.variable} ${roboto.variable}`}>
          {/* If Route is /login, remove header */}
          <LayoutProvider>
            <div className="max-w-6xl mx-auto">{children}</div>
          </LayoutProvider>
        </body>
      </Providers>
    </html>
  );
}
